<?php

namespace ContainerDmeScoD;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmpresaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0T4o.Jo.App\Entity\Empresa' shared service.
     *
     * @return \App\Entity\Empresa
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0T4o.Jo": it needs an instance of "App\\Entity\\Empresa" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
