<?php

namespace ContainerKhirob6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NeGtyROService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NeGtyRO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NeGtyRO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'empresa' => ['privates', '.errored..service_locator.NeGtyRO.App\\Entity\\Empresa', NULL, 'Cannot autowire service ".service_locator.NeGtyRO": it needs an instance of "App\\Entity\\Empresa" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'empresa' => 'App\\Entity\\Empresa',
        ]);
    }
}
