<?php

namespace ContainerKhirob6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TPz26_UService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tPz26.u' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'empresa' => ['privates', '.errored..service_locator.tPz26.u.App\\Entity\\Empresa', NULL, 'Cannot autowire service ".service_locator.tPz26.u": it needs an instance of "App\\Entity\\Empresa" but this type has been excluded because it\'s a Doctrine entity.'],
            'gestor' => ['privates', 'App\\Service\\GestorSftpService', 'getGestorSftpServiceService', true],
        ], [
            'empresa' => 'App\\Entity\\Empresa',
            'gestor' => 'App\\Service\\GestorSftpService',
        ]);

        if (isset($container->privates['.service_locator.tPz26.u'])) {
            return $container->privates['.service_locator.tPz26.u'];
        }

        return $container->privates['.service_locator.tPz26.u'] = $instance;
    }
}
