<?php

namespace ContainerKhirob6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmpresaControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0T4o.Jo.App\Controller\EmpresaController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'empresa' => ['privates', '.errored..service_locator.0T4o.Jo.App\\Entity\\Empresa', NULL, 'Cannot autowire service ".service_locator.0T4o.Jo": it needs an instance of "App\\Entity\\Empresa" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'empresa' => 'App\\Entity\\Empresa',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\EmpresaController::delete()', $container);

        if (isset($container->privates['.service_locator.0T4o.Jo.App\\Controller\\EmpresaController::delete()'])) {
            return $container->privates['.service_locator.0T4o.Jo.App\\Controller\\EmpresaController::delete()'];
        }

        return $container->privates['.service_locator.0T4o.Jo.App\\Controller\\EmpresaController::delete()'] = $instance;
    }
}
