<?php

namespace ContainerKhirob6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmpresaControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0zQYJDq.App\Controller\EmpresaController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0zQYJDq.App\\Controller\\EmpresaController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'empresa' => ['privates', '.errored..service_locator.0zQYJDq.App\\Entity\\Empresa', NULL, 'Cannot autowire service ".service_locator.0zQYJDq": it needs an instance of "App\\Entity\\Empresa" but this type has been excluded because it\'s a Doctrine entity.'],
            'empresaRepository' => ['privates', 'App\\Repository\\EmpresaRepository', 'getEmpresaRepositoryService', true],
        ], [
            'empresa' => 'App\\Entity\\Empresa',
            'empresaRepository' => 'App\\Repository\\EmpresaRepository',
        ]))->withContext('App\\Controller\\EmpresaController::edit()', $container);
    }
}
