<?php

namespace ContainerKhirob6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmpresaControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KNeXB3r.App\Controller\EmpresaController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KNeXB3r.App\\Controller\\EmpresaController::index()'] = ($container->privates['.service_locator.KNeXB3r'] ?? $container->load('get_ServiceLocator_KNeXB3rService'))->withContext('App\\Controller\\EmpresaController::index()', $container);
    }
}
