<?php

namespace ContainerKhirob6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExploradorControllerempresaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NeGtyRO.App\Controller\ExploradorController::empresa()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NeGtyRO.App\\Controller\\ExploradorController::empresa()'] = ($container->privates['.service_locator.NeGtyRO'] ?? $container->load('get_ServiceLocator_NeGtyROService'))->withContext('App\\Controller\\ExploradorController::empresa()', $container);
    }
}
