<?php

namespace ContainerKhirob6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExploradorControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2moJ9zp.App\Controller\ExploradorController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2moJ9zp.App\\Controller\\ExploradorController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\EmpresaRepository', 'getEmpresaRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\EmpresaRepository',
        ]))->withContext('App\\Controller\\ExploradorController::index()', $container);
    }
}
