<?php

namespace ContainerW7QGi7L;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__RvfVlIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..rvfVlI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\EmpresaController::index' => ['privates', '.service_locator.KNeXB3r.App\\Controller\\EmpresaController::index()', 'getEmpresaControllerindexService', true],
            'App\\Controller\\EmpresaController::new' => ['privates', '.service_locator.KNeXB3r.App\\Controller\\EmpresaController::new()', 'getEmpresaControllernewService', true],
            'App\\Controller\\EmpresaController::show' => ['privates', '.service_locator.NeGtyRO.App\\Controller\\EmpresaController::show()', 'getEmpresaControllershowService', true],
            'App\\Controller\\EmpresaController::edit' => ['privates', '.service_locator.0zQYJDq.App\\Controller\\EmpresaController::edit()', 'getEmpresaControllereditService', true],
            'App\\Controller\\EmpresaController::delete' => ['privates', '.service_locator.0T4o.Jo.App\\Controller\\EmpresaController::delete()', 'getEmpresaControllerdeleteService', true],
            'App\\Controller\\ExploradorController::index' => ['privates', '.service_locator.2moJ9zp.App\\Controller\\ExploradorController::index()', 'getExploradorControllerindexService', true],
            'App\\Controller\\ExploradorController::empresa' => ['privates', '.service_locator.tPz26.u.App\\Controller\\ExploradorController::empresa()', 'getExploradorControllerempresaService', true],
            'App\\Controller\\ExploradorController::archivosJson' => ['privates', '.service_locator.tPz26.u.App\\Controller\\ExploradorController::archivosJson()', 'getExploradorControllerarchivosJsonService', true],
            'App\\Controller\\ExploradorController::subir' => ['privates', '.service_locator.tPz26.u.App\\Controller\\ExploradorController::subir()', 'getExploradorControllersubirService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\EmpresaController:index' => ['privates', '.service_locator.KNeXB3r.App\\Controller\\EmpresaController::index()', 'getEmpresaControllerindexService', true],
            'App\\Controller\\EmpresaController:new' => ['privates', '.service_locator.KNeXB3r.App\\Controller\\EmpresaController::new()', 'getEmpresaControllernewService', true],
            'App\\Controller\\EmpresaController:show' => ['privates', '.service_locator.NeGtyRO.App\\Controller\\EmpresaController::show()', 'getEmpresaControllershowService', true],
            'App\\Controller\\EmpresaController:edit' => ['privates', '.service_locator.0zQYJDq.App\\Controller\\EmpresaController::edit()', 'getEmpresaControllereditService', true],
            'App\\Controller\\EmpresaController:delete' => ['privates', '.service_locator.0T4o.Jo.App\\Controller\\EmpresaController::delete()', 'getEmpresaControllerdeleteService', true],
            'App\\Controller\\ExploradorController:index' => ['privates', '.service_locator.2moJ9zp.App\\Controller\\ExploradorController::index()', 'getExploradorControllerindexService', true],
            'App\\Controller\\ExploradorController:empresa' => ['privates', '.service_locator.tPz26.u.App\\Controller\\ExploradorController::empresa()', 'getExploradorControllerempresaService', true],
            'App\\Controller\\ExploradorController:archivosJson' => ['privates', '.service_locator.tPz26.u.App\\Controller\\ExploradorController::archivosJson()', 'getExploradorControllerarchivosJsonService', true],
            'App\\Controller\\ExploradorController:subir' => ['privates', '.service_locator.tPz26.u.App\\Controller\\ExploradorController::subir()', 'getExploradorControllersubirService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\EmpresaController::index' => '?',
            'App\\Controller\\EmpresaController::new' => '?',
            'App\\Controller\\EmpresaController::show' => '?',
            'App\\Controller\\EmpresaController::edit' => '?',
            'App\\Controller\\EmpresaController::delete' => '?',
            'App\\Controller\\ExploradorController::index' => '?',
            'App\\Controller\\ExploradorController::empresa' => '?',
            'App\\Controller\\ExploradorController::archivosJson' => '?',
            'App\\Controller\\ExploradorController::subir' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\EmpresaController:index' => '?',
            'App\\Controller\\EmpresaController:new' => '?',
            'App\\Controller\\EmpresaController:show' => '?',
            'App\\Controller\\EmpresaController:edit' => '?',
            'App\\Controller\\EmpresaController:delete' => '?',
            'App\\Controller\\ExploradorController:index' => '?',
            'App\\Controller\\ExploradorController:empresa' => '?',
            'App\\Controller\\ExploradorController:archivosJson' => '?',
            'App\\Controller\\ExploradorController:subir' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);

        if (isset($container->privates['.service_locator..rvfVlI'])) {
            return $container->privates['.service_locator..rvfVlI'];
        }

        return $container->privates['.service_locator..rvfVlI'] = $instance;
    }
}
