<?php

namespace ContainerW7QGi7L;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExploradorControllersubirService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tPz26.u.App\Controller\ExploradorController::subir()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.tPz26.u'] ?? $container->load('get_ServiceLocator_TPz26_UService'));

        if (isset($container->privates['.service_locator.tPz26.u.App\\Controller\\ExploradorController::subir()'])) {
            return $container->privates['.service_locator.tPz26.u.App\\Controller\\ExploradorController::subir()'];
        }

        $instance = $a->withContext('App\\Controller\\ExploradorController::subir()', $container);

        if (isset($container->privates['.service_locator.tPz26.u.App\\Controller\\ExploradorController::subir()'])) {
            return $container->privates['.service_locator.tPz26.u.App\\Controller\\ExploradorController::subir()'];
        }

        return $container->privates['.service_locator.tPz26.u.App\\Controller\\ExploradorController::subir()'] = $instance;
    }
}
