<?php

namespace ContainerW7QGi7L;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmpresa4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tPz26.u.App\Entity\Empresa' shared service.
     *
     * @return \App\Entity\Empresa
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.tPz26.u": it needs an instance of "App\\Entity\\Empresa" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
