<?php

namespace Container57HsnbD;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JE5QQaDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JE5QQaD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\EmpresaController::index' => ['privates', '.service_locator.KNeXB3r.App\\Controller\\EmpresaController::index()', 'getEmpresaControllerindexService', true],
            'App\\Controller\\EmpresaController::new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\EmpresaController::new()', 'getEmpresaControllernewService', true],
            'App\\Controller\\EmpresaController::edit' => ['privates', '.service_locator.0T4o.Jo.App\\Controller\\EmpresaController::edit()', 'getEmpresaControllereditService', true],
            'App\\Controller\\EmpresaController::delete' => ['privates', '.service_locator.0T4o.Jo.App\\Controller\\EmpresaController::delete()', 'getEmpresaControllerdeleteService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\EmpresaController:index' => ['privates', '.service_locator.KNeXB3r.App\\Controller\\EmpresaController::index()', 'getEmpresaControllerindexService', true],
            'App\\Controller\\EmpresaController:new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\EmpresaController::new()', 'getEmpresaControllernewService', true],
            'App\\Controller\\EmpresaController:edit' => ['privates', '.service_locator.0T4o.Jo.App\\Controller\\EmpresaController::edit()', 'getEmpresaControllereditService', true],
            'App\\Controller\\EmpresaController:delete' => ['privates', '.service_locator.0T4o.Jo.App\\Controller\\EmpresaController::delete()', 'getEmpresaControllerdeleteService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\EmpresaController::index' => '?',
            'App\\Controller\\EmpresaController::new' => '?',
            'App\\Controller\\EmpresaController::edit' => '?',
            'App\\Controller\\EmpresaController::delete' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\EmpresaController:index' => '?',
            'App\\Controller\\EmpresaController:new' => '?',
            'App\\Controller\\EmpresaController:edit' => '?',
            'App\\Controller\\EmpresaController:delete' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);

        if (isset($container->privates['.service_locator.JE5QQaD'])) {
            return $container->privates['.service_locator.JE5QQaD'];
        }

        return $container->privates['.service_locator.JE5QQaD'] = $instance;
    }
}
