<?php

namespace Container57HsnbD;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmpresaControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0T4o.Jo.App\Controller\EmpresaController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.0T4o.Jo'] ?? $container->load('get_ServiceLocator_0T4o_JoService'));

        if (isset($container->privates['.service_locator.0T4o.Jo.App\\Controller\\EmpresaController::delete()'])) {
            return $container->privates['.service_locator.0T4o.Jo.App\\Controller\\EmpresaController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\EmpresaController::delete()', $container);

        if (isset($container->privates['.service_locator.0T4o.Jo.App\\Controller\\EmpresaController::delete()'])) {
            return $container->privates['.service_locator.0T4o.Jo.App\\Controller\\EmpresaController::delete()'];
        }

        return $container->privates['.service_locator.0T4o.Jo.App\\Controller\\EmpresaController::delete()'] = $instance;
    }
}
