<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPfhoXTc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPfhoXTc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPfhoXTc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPfhoXTc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPfhoXTc\App_KernelDevDebugContainer([
    'container.build_hash' => 'PfhoXTc',
    'container.build_id' => '7cc7625a',
    'container.build_time' => 1776507965,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPfhoXTc');
