<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDPCLTAs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDPCLTAs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDPCLTAs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDPCLTAs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDPCLTAs\App_KernelDevDebugContainer([
    'container.build_hash' => 'DPCLTAs',
    'container.build_id' => 'd9cb10c6',
    'container.build_time' => 1776951013,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDPCLTAs');
